services:
  waline:
    image: ghcr.io/beiyanyunyi/waline-docker-slim:edge
    build:
      context: .
    environment:
      - "SQLITE_PATH=./data"
      - "CLASS_IT_UP_API=http://class-it-up:8000/predict"
    env_file:
      - ./.env
    volumes:
      - ./data:/app/data
    ports:
      - "127.0.0.1:8360:8360"
  class-it-up:
    image: ghcr.io/beiyanyunyi/class-it-up:edge
